name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: controle_estoque
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json
            tests/package-lock.json

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Install Test Dependencies
        working-directory: ./tests
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./tests
        run: npx playwright install --with-deps chromium

      - name: Setup Database
        working-directory: ./backend
        run: |
          mysql -h 127.0.0.1 -u root -proot controle_estoque < database/schema.sql

      - name: Start Backend
        working-directory: ./backend
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_USER=.*/DB_USER=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env
          sed -i 's/DB_NAME=.*/DB_NAME=controle_estoque/' .env
          npm run dev &
          sleep 5
        env:
          NODE_ENV: test

      - name: Start Frontend
        working-directory: ./frontend
        run: |
          npm run dev &
          sleep 10

      - name: Run E2E Tests
        working-directory: ./tests
        run: npx playwright test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 30

      - name: Upload Test Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: tests/test-results/
          retention-days: 7
